### ISSUE TITLE
Encoding error on Debian

### ISSUE THREAD

**Issue by hertzigger** [barneygale/mark2#106]
Hi when i am trying to do mark2 attach I get the current error

Traceback (most recent call last):
  File "/usr/local/bin/mark2", line 9, in <module>
    load_entry_point('mark2==0.1.4.2', 'console_scripts', 'mark2')()
  File "/usr/local/lib/python2.7/dist-packages/mk2/launcher.py", line 605, in main
    command.start()
  File "/usr/local/lib/python2.7/dist-packages/mk2/launcher.py", line 126, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mk2/launcher.py", line 501, in run
    f.main()
  File "/usr/local/lib/python2.7/dist-packages/mk2/user_client.py", line 472, in main
    self.ui.main()
  File "/usr/local/lib/python2.7/dist-packages/mk2/user_client.py", line 250, in main
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 312, in _run
    self.draw_screen()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 563, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 564, in render
    canv = self._original_widget.render((maxcol,)+size[1:], focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1049, in render
    focus and self.focus_part == 'header')
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 2055, in render
    focus = focus and self.focus_position == i)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 2055, in render
    focus = focus and self.focus_position == i)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 1008, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/local/lib/python2.7/dist-packages/urwid/canvas.py", line 1291, in apply_text_layout
    text[s.offs:s.end])
  File "/usr/local/lib/python2.7/dist-packages/urwid/util.py", line 121, in apply_target_encoding
    s = s.encode( _target_encoding )
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u21c9' in position 7: ordinal not in range(256)

**Comment by barneygale** [comment]
Have a look at this: http://fruit.je/utf-8

**Comment by ekondrashyn** [comment]
It helped. Many thanks!
