### ISSUE TITLE
Where can we locate the config/mark2.properties?

### ISSUE THREAD

**Issue by badnatho** [barneygale/mark2#136]
I have been trying out mark2 for my bungee servers but I cannot figure out where the default mark2.properties file is. Could someone please help me. [Running CentOs 6]

**Comment by badnatho** [comment]
Tried the mark2 config:

```
[admin@ks4000277 ~]$ mark2 config
Traceback (most recent call last):
  File "/usr/bin/mark2", line 9, in <module>
    load_entry_point('mark2==0.1.4.3', 'console_scripts', 'mark2')()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.3-py2.6.egg/mk2/launcher.py", line 605, in main
    command.start()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.3-py2.6.egg/mk2/launcher.py", line 126, in start
    self.run()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.3-py2.6.egg/mk2/launcher.py", line 479, in run
    subprocess.call([editor, path_tmp])
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by gsand** [comment]
you have to run it as root, iirc.

**Comment by Brottweiler** [comment]
@gsand Correct, though I recall you getting a permission error when running without root, but I might be mistaken.
`sudo mark2 config`
What you edit here, is what's going to end up in `/etc/mark2/mark2.properties`, then you should make a `mark2.properties` in your server dir if you want to change anything else specifically for that server.

**Comment by badnatho** [comment]
Yeah, I tried the config again as root and sudo 

```
[root@ks4000277 ~]# sudo mark2 config
Traceback (most recent call last):
  File "/usr/bin/mark2", line 9, in <module>
    load_entry_point('mark2==0.1.4.3', 'console_scripts', 'mark2')()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.3-py2.6.egg/mk2/launcher.py", line 605, in main
    command.start()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.3-py2.6.egg/mk2/launcher.py", line 126, in start
    self.run()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.3-py2.6.egg/mk2/launcher.py", line 479, in run
    subprocess.call([editor, path_tmp])
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@ks4000277 ~]# 
```

**Comment by badnatho** [comment]
Bump Its been a few days. Still not resolved for me. thinking about a clean reinstall.
