### ISSUE TITLE
mark2 attach does not work

### ISSUE THREAD

**Issue by tjsd** [barneygale/mark2#151]
Running Ubuntu 13.10 64bit.

Command:
mark2 attach

Errormsg:
Traceback (most recent call last):
  File "/usr/bin/mark2", line 6, in <module>
    sys.exit(main())
  File "/home/minecraft/mark2/mk2/launcher.py", line 605, in main
    command.start()
  File "/home/minecraft/mark2/mk2/launcher.py", line 126, in start
    self.run()
  File "/home/minecraft/mark2/mk2/launcher.py", line 500, in run
    f = user_client.UserClientFactory(self.server_name, self.shared_path)
  File "/home/minecraft/mark2/mk2/user_client.py", line 448, in **init**
    self.ui = UI(self.config.get_palette(), self.get_players, self.run_command, self.switch_server, self.connect_to_server, self.config.get_player_actions(), self.config.get_player_reasons())
  File "/home/minecraft/mark2/mk2/user_client.py", line 210, in **init**
    self.build()
  File "/home/minecraft/mark2/mk2/user_client.py", line 216, in build
    g_head         = urwid.AttrMap(urwid.Columns((self.g_servers, self.g_users)), 'head')
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1092, in **init**
    if focus_column is None and w.selectable():
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1411, in selectable
    return self.widget_list[self.focus_col].selectable()
IndexError: list index out of range

**Comment by xandiko** [comment]
This problem is urwid version related.
You must use  python-urwid >= 1.1.0

**Comment by Silthus** [comment]
Got the same problem and I have version 1.2.1 of urwid installed:

(! 5998)-> pip search urwid
urwid                     - A full-featured console (xterm et al.) user interface library
  INSTALLED: 1.2.1 (latest)

// EDIT: Problems seems to be the debian package is version: 1.0.1-2

But when I remove it and install via PIP it does says no package urwid found.
