### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by aaomidi** [barneygale/mark2#156]
root@mc-0 [/mc/mark2]# mark2 config
Traceback (most recent call last):
  File "/usr/bin/mark2", line 6, in <module>
    sys.exit(main())
  File "/mc/mark2/mk2/launcher.py", line 610, in main
    command.start()
  File "/mc/mark2/mk2/launcher.py", line 126, in start
    self.run()
  File "/mc/mark2/mk2/launcher.py", line 469, in run
    if self.check_executable(editor):
  File "/mc/mark2/mk2/launcher.py", line 414, in check_executable
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Running Ubuntu 14.04

Edit: I was able to set it up by using per server config and making a fake configuration file in /etc/mark2
with the command:

```
sudo touch /etc/mark2/mark2.properties
```

A good guide: https://gist.github.com/vemacs/5663144

I would still like to know the reason for mark2 config erroring like that.

Edit 2: Looks like the new commit has a problem with reading the files! Thanks for @ShepherdJerred for pointing me out to a file version thats actually working!
https://github.com/mcdevs/mark2/blob/23d61ab5e129ecd5e5e205caaf383629c4abb0df/mk2/launcher.py

**Comment by shepherdjerred** [comment]
I've found that the latest commit to the launcher.py causes this issue, using the version from July 16th and this error no longer occurs. Using Ubuntu 14.04 as well.

Link to older version of launcher.py: https://github.com/mcdevs/mark2/blob/23d61ab5e129ecd5e5e205caaf383629c4abb0df/mk2/launcher.py

**Comment by aaomidi** [comment]
Thank you, this helped!
