### ISSUE TITLE
Error when starting mark2

### ISSUE THREAD

**Issue by SupaYoshi** [barneygale/mark2#24]
Hello I am getting this error when i try to start mark2

sup4y0sh1@unitedfactions:~$ mark2 start
2013-02-21 12:41:49 # mark2 starting...
2013-02-21 12:41:49 # file doesn't exist: scripts.txt
2013-02-21 12:41:49 # starting minecraft server
2013-02-21 12:41:49 | [???] Upon execvpe java ['java', '-Xms2800M', '-Xmx8000M', '-jar', 'craftbukkit.jar', 'nogui'] in environment id 8970912
2013-02-21 12:41:49 | [???] :Traceback (most recent call last):
2013-02-21 12:41:49 | [???] File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 414, in _fork
2013-02-21 12:41:49 | [???] executable, args, environment)
2013-02-21 12:41:49 | [???] File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 460, in _execChild
2013-02-21 12:41:49 | [???] os.execvpe(executable, args, environment)
2013-02-21 12:41:49 | [???] File "/usr/lib/python2.7/os.py", line 353, in execvpe
2013-02-21 12:41:49 | [???] _execvpe(file, args, env)
2013-02-21 12:41:49 | [???] File "/usr/lib/python2.7/os.py", line 380, in _execvpe
2013-02-21 12:41:49 | [???] func(fullname, *argrest)
2013-02-21 12:41:49 | [???] OSError: [Errno 2] No such file or directory
2013-02-21 12:41:49 # fatal error: A process has ended with a probable error condition: process ended with exit code 1.
2013-02-21 12:41:49 # mark2 stopped.

**Comment by edk0** [comment]
This issue seems to be a consequence of not having java installed, closing
