### ISSUE TITLE
~events throw error

### ISSUE THREAD

**Issue by Algent** [barneygale/mark2#69]
Using ~events command return me the following error:

``` bash
2013-05-16 13:15:14 > (minecraft) ~events
2013-05-16 13:15:14 # The following events are available:
2013-05-16 13:15:14 # An event handler threw an exception: 
2013-05-16 13:15:14 #   Callback: <bound method Manager.handle_cmd_events of <manager.Manager instance at 0x22c2ab8>>
2013-05-16 13:15:14 #   Event: 
2013-05-16 13:15:14 #     class_name: Hook
2013-05-16 13:15:14 #     line: ~events
2013-05-16 13:15:14 #     args: None
2013-05-16 13:15:14 #     is_command: True
2013-05-16 13:15:14 #     name: events
2013-05-16 13:15:14 #   Traceback (most recent call last):
2013-05-16 13:15:14 #     File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
2013-05-16 13:15:14 #       result = g.send(result)
2013-05-16 13:15:14 #     File "/home/minecraft/utils/mark2/manager.py", line 309, in handle_user_input
2013-05-16 13:15:14 #       handled = yield self.events.dispatch(events.Hook(line=event.line))
2013-05-16 13:15:14 #     File "/home/minecraft/utils/mark2/events/__init__.py", line 236, in dispatch
2013-05-16 13:15:14 #       d = self._next_event(event, event_list)
2013-05-16 13:15:14 #     File "/home/minecraft/utils/mark2/events/__init__.py", line 216, in _next_event
2013-05-16 13:15:14 #       r = maybeDeferred(callback, event)
2013-05-16 13:15:14 #   --- <exception caught here> ---
2013-05-16 13:15:14 #     File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 134, in maybeDeferred
2013-05-16 13:15:14 #       result = f(*args, **kw)
2013-05-16 13:15:14 #     File "/home/minecraft/utils/mark2/manager.py", line 229, in handle_cmd_events
2013-05-16 13:15:14 #       self.table([(n, c.doc) for n, c in events.get_all()])
2013-05-16 13:15:14 #   exceptions.AttributeError: type object 'Console' has no attribute 'doc'
```

**Comment by edk0** [comment]
thanks!
