### ISSUE TITLE
Forge's patching breaks mark2

### ISSUE THREAD

**Issue by vemacs** [barneygale/mark2#87]
Using Forge's universal JAR in the same directory as the minecraft_server vanilla JAR causes mark2 to output this:

```
2013-06-18 11:19:01 # mark2 starting...
2013-06-18 11:19:01 # service: 'console_tracking' failed to initialize
2013-06-18 11:19:01 # Traceback (most recent call last):
2013-06-18 11:19:01 #   File "/usr/mark2/mk2/plugins/__init__.py", line 326, in load
2013-06-18 11:19:01 #     plugin = cls(self.parent, name, **kwargs)
2013-06-18 11:19:01 #   File "/usr/mark2/mk2/plugins/__init__.py", line 167, in __init__
2013-06-18 11:19:01 #     self.setup()
2013-06-18 11:19:01 #   File "/usr/mark2/mk2/services/console_tracking.py", line 13, in setup
2013-06-18 11:19:01 #     lang = properties.load_jar(self.parent.jar_file, 'lang/en_US.lang')
2013-06-18 11:19:01 #   File "/usr/mark2/mk2/properties.py", line 21, in load_jar
2013-06-18 11:19:01 #     o = Lang(z.open(path, 'r'))
2013-06-18 11:19:01 #   File "/usr/lib/python2.7/zipfile.py", line 892, in open
2013-06-18 11:19:01 #     zinfo = self.getinfo(name)
2013-06-18 11:19:01 #   File "/usr/lib/python2.7/zipfile.py", line 859, in getinfo
2013-06-18 11:19:01 #     'There is no item named %r in the archive' % name)
2013-06-18 11:19:01 # KeyError: "There is no item named 'lang/en_US.lang' in the archive"
2013-06-18 11:19:01 #
2013-06-18 11:19:01 # fatal error: couldn't load service: 'console_tracking'
2013-06-18 11:19:01 # mark2 stopped.
```

However, using `java -Xms768 -Xmx1024M -jar forge.jar` works fine. Similar setups, such as Tekkit's default one, also have this issue.

**Comment by Brottweiler** [comment]
Related to https://github.com/mcdevs/mark2/issues/85?

**Comment by vemacs** [comment]
Forge starts now, but mark2 doesn't exit after it finishes starting. I had to Ctrl+C it.

`2013-06-20 17:12:26 | [Minecraft-Server] /127.0.0.1:37367 lost connection` appears, probably mark2's server list ping, before it (mark2) freezes.

**Comment by barneygale** [comment]
Should be good now. Confirm?

**Comment by vemacs** [comment]
https://github.com/mcdevs/mark2/commit/c9b834e0c0cad7bdfd4290073aafd7448b83cc3c fixed it.
