### ISSUE TITLE
Crash when attempting to stop the server

### ISSUE THREAD

**Issue by Nullreff** [barneygale/mark2#94]
Running

```
$ mark2 stop
```

outputs

```
2013-07-03 21:58:41 > (@external) ~stop
      Callback: <bound method Shutdown.h_stop of <shutdown.Shutdown object at 0xa562a6c>>
      Event:
        class_name: Hook
        line: ~stop
        args: None
        is_command: True
        name: stop
2013-07-03 21:58:41 # An event handler threw an exception:
2013-07-03 21:58:41 #   Callback: <bound method Shutdown.h_stop of <shutdown.Shutdown object at 0xa562a6c>>
2013-07-03 21:58:41 #   Event:
2013-07-03 21:58:41 #     class_name: Hook
2013-07-03 21:58:41 #     line: ~stop
2013-07-03 21:58:41 #     args: None
2013-07-03 21:58:41 #     is_command: True
2013-07-03 21:58:41 #     name: stop
2013-07-03 21:58:41 #   Traceback (most recent call last):
2013-07-03 21:58:41 #     File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1070, in _inlineCallbacks
2013-07-03 21:58:41 #       result = g.send(result)
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/manager.py", line 217, in handle_user_input
2013-07-03 21:58:41 #       handled = yield self.events.dispatch(events.Hook(line=event.line))
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/events/__init__.py", line 238, in dispatch
2013-07-03 21:58:41 #       d = self._next_event(event, event_list)
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/events/__init__.py", line 218, in _next_event
2013-07-03 21:58:41 #       r = maybeDeferred(callback, event)
2013-07-03 21:58:41 #   --- <exception caught here> --- 
2013-07-03 21:58:41 #     File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 137, in maybeDeferred
2013-07-03 21:58:41 #       result = f(*args, **kw)
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/plugins/shutdown.py", line 95, in h_stop
2013-07-03 21:58:41 #       action()
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/plugins/shutdown.py", line 91, in <lambda>
2013-07-03 21:58:41 #       action = lambda: self.nice_stop(False, False)
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/plugins/shutdown.py", line 58, in nice_stop
2013-07-03 21:58:41 #       self.send('save-all')
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/plugins/__init__.py", line 239, in send
2013-07-03 21:58:41 #       self.dispatch(ServerInput(line=l, parse_colors=parseColors))
2013-07-03 21:58:41 #     File "/opt/mark2/mk2/events/__init__.py", line 53, in __init__
2013-07-03 21:58:41 #       format(self.__class__.__name__, ", ".join(excess)))
2013-07-03 21:58:41 #   exceptions.Exception: Event type ServerInput got extraneous argument(s): parse_colors
2013-07-03 21:58:41 #
```

**Comment by Nullreff** [comment]
Looks like this was fixed in 5c54ed63bb05b6761a140a4738b1427d98df32df.  I've updated and its working now.
