### ISSUE TITLE
mark2 config error

### ISSUE THREAD

**Issue by rmb938** [barneygale/mark2#99]
When I run mark2 config I get this error:

[rmb938@centos-vm spigot]$ mark2 config
Traceback (most recent call last):
  File "/usr/bin/mark2", line 9, in <module>
    load_entry_point('mark2==0.1.4.1', 'console_scripts', 'mark2')()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.1-py2.6.egg/mk2/launcher.py", line 605, in main
    command.start()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.1-py2.6.egg/mk2/launcher.py", line 126, in start
    self.run()
  File "/usr/lib/python2.6/site-packages/mark2-0.1.4.1-py2.6.egg/mk2/launcher.py", line 479, in run
    subprocess.call([editor, path_tmp])
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(_popenargs, *_kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I made sure everything is installed correctly so I have no idea why it is giving this error.

**Comment by rmb938** [comment]
Well it seems I didn't have $EDITOR set. I set it and the issue was fixed.
